"""add ticket comment mentions

Revision ID: 706b2057034b
Revises: 6e3d07204094
Create Date: 2026-09-05 21:03:38.120007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '706b2057034b'
down_revision: Union[str, Sequence[str], None] = '6e3d07204094'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_comment_mentions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('mentioned_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['ticket_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mentioned_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_comment_mentions_comment_id'), 'ticket_comment_mentions', ['comment_id'], unique=False)
    op.create_index(op.f('ix_ticket_comment_mentions_mentioned_user_id'), 'ticket_comment_mentions', ['mentioned_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_comment_mentions_mentioned_user_id'), table_name='ticket_comment_mentions')
    op.drop_index(op.f('ix_ticket_comment_mentions_comment_id'), table_name='ticket_comment_mentions')
    op.drop_table('ticket_comment_mentions')
    # ### end Alembic commands ###
